/*
Copyright (C) 1992-1994 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

/* generated by sndlink.exe */

enum {
SND_NOSOUND,
SND_THROWSWITCH, /* Throw end level switch */
SND_GETKEY,		/* Pick up a key */
SND_BONUS,		/* Score ding */
SND_OPENDOOR,	/* Open a door */
SND_DOGBARK,	/* Dog bite */
SND_DOGDIE,		/* Dog die */
SND_ESEE,		/* Ahtung! */
SND_ESEE2,		/* Halt! */
SND_EDIE,		/* Nazi died */
SND_EDIE2,		/* Nazi died 2 */
SND_BODYFALL,	/* Body hit the ground */
SND_PAIN,		/* Hit bad guy */
SND_GETAMMO,	/* Pick up ammo */
SND_KNIFE,		/* Knife attack */
SND_GUNSHT,		/* 45 Shoot */
SND_MGUN,		/* Sub machine gun */
SND_CHAIN,		/* Chain gun */
SND_FTHROW,		/* Flame thrower */
SND_ROCKET,		/* Rocket launcher */	
SND_PWALL,		/* Start pushwall */
SND_PWALL2,		/* Stop pushwall */
SND_GUTEN,		/* Guten tag */
SND_SHIT,		/* Shit! */
SND_HEAL,		/* Healed a bit */
SND_THUMBSUP,	/* You stud you! */
SND_EXTRA,		/* Extra guy */
SND_OUCH1,		/* BJ has beed injured */
SND_OUCH2,		/* Second sound */
SND_PDIE,		/* BJ has died */
SND_HITWALL,	/* Tried to open a wall */
SND_KNIFEMISS,	/* Knife missed */
SND_BIGGUN,		/* Boss's gun */
SND_COMEHERE,	/* Come here! */
SND_ESEE3,		/* Nazi sees you */
SND_ESEE4,		/* Nazi sees you */
SND_OK,			/* Hit start game */
SND_MENU,		/* New game menu */
SND_HITLERSEE,	/* Hitler sees you */
SND_SHITHEAD,	/* Big boss sees you */
SND_BOOM,		/* Explosion */
SND_LOCKEDDOOR,	/* Locked door */
SND_MECHSTEP,	/* Mech step */
NUMSOUNDS };
